### PR TITLE
style(margin): adjust margin to not apply when scrolling #55

### PR DESCRIPTION
**Pull request by gusnaughton**
# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #55 

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

The scope of this update is to move the responsibility of the top padding from the outer container to the header element for placement. 

This addresses an issue where internal content may want to scroll to the top, but is being stopped by the inset padding. 

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

### CODE REVIEW

**Comment by braven112** [comment]
Looks like this change would mess up the top padding on initial load of the drawer since that is set to zero.

**Comment by gusnaughton** [comment]
> Looks like this change would mess up the top padding on initial load of the drawer since that is set to zero.

The header slot has padding set on it regardless if there's content or not which should serve the same purpose. Do you see this bug in your local?

**Comment by blackfalcon** [comment]
A few things. 

1. I updated to code to minimize the dupe CSS
2. Added a fix to the demo/index.html file per issues with the new version of marked
3. Updated initial commit message to use [fix](https://www.conventionalcommits.org/en/v1.0.0/#specification) vs [style](https://gist.github.com/qoomon/5dfcdf8eec66a051ecd85625518cfd13#:~:text=style%20Commits%2C%20that%20do%20not,tests%20or%20correcting%20existing%20tests) (please click links to see why)

**Review by blackfalcon — APPROVED** [review]

**Pull request merged**
