### PR TITLE
fix bundle paths

### PR DESCRIPTION
**Pull request by jason-capsule42**
# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #62 

## Summary:

This change update the incorrect paths in the readme for the bundle install information.

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

### CODE REVIEW

**Review by blackfalcon — CHANGES_REQUESTED** [review]
Not sure what happened here? It appears that the commit for this was merged into the last commit from the release bot?

**Comment by jason-capsule42** [comment]
> Not sure what happened here? It appears that the commit for this was merged into the last commit from the release bot?

I don't know what the change requested here is.

**Comment by blackfalcon** [comment]
> > Not sure what happened here? It appears that the commit for this was merged into the last commit from the release bot?
> 
> I don't know what the change requested here is.

Your commit here is merged with the previous RELEASE commit. 

Screen Shot 2022-01-13 at 11 32 13 AM

**Comment by blackfalcon** [comment]
This draft PR has been open for 19 days. Has this work been resolved in another branch or PR?

**Pull request closed without merging**
